### ISSUE TITLE
Cors issue tower file input example

### ISSUE THREAD

**Issue by atudz** [StrutTower/tower-file-input#4]
<img width="1471" alt="Screenshot 2019-12-13 at 10 30 01 PM" src="https://user-images.githubusercontent.com/11872826/70807302-3ebead80-1df8-11ea-9246-d748b60f6f76.png">

**Comment by StrutTower** [comment]
I've rewritten the entire demo page and I'm not getting any CORS errors now. I believe that was left over from using an old third party site to render static content from a GitHub repository
